Implement printErrorsAndExitIfAny().

diff --git a/.env/bin/hdawscf b/.env/bin/hdawscf
--- a/.env/bin/hdawscf
+++ b/.env/bin/hdawscf
@@ -98,6 +98,29 @@ FILES=("$@") # If you want the number of elements of $@, use $#
 # VALIDATION
 # ════════════════════════════════════════════════════════════════════
 
+printErrorsAndExitIfAny()
+{
+  printWarnings
+  if [ ! -z "${ERRORS}" ]; then
+    echo -e "${ANSI[FG_WHITE_BG_RED]}ERROR:${ANSI[RESET]}  The following errors where detected.\n"
+    echo -e "${ANSI[FG_WHITE_BG_RED]}ERREUR:${ANSI[RESET]}  Les erreurs suivantes furent détectées.\n"
+    echo -e "${ERRORS}"
+    echo -e "Command aborted."
+    echo -e "Commande avortée."
+    exit 1
+  fi
+}
+
+printWarnings()
+{
+  if [ ! -z "${WARNINGS}" ]; then
+    echo -e "${ANSI[FG_BLACK_BG_YELLOW]}WARNING:${ANSI[RESET]}  The following warnings were thrown.\n"
+    echo -e "${ANSI[FG_BLACK_BG_YELLOW]}AVERTISSEMENT:${ANSI[RESET]}  Les avertissement suivants furent lancés.\n"
+    echo -e "${WARNINGS}"
+  fi
+}
+
+WARNINGS=""
 ERRORS=""
 
 if ((${#FILES[*]} == 0)); then
@@ -112,12 +135,7 @@ if [ ! -z "${PARAMETERS}" ]; then
   fi
 fi
 
-if [ ! -z "${ERRORS}" ]; then
-  echo -e "\e[1;37;41mERROR:\e[0m  The following errors where detected.\n"
-  echo -e "${ERRORS}"
-  echo -e "Command aborted."
-  exit 1
-fi
+printErrorsAndExitIfAny
 
 TIMESTAMP_FORMAT_HUMAN="%Y-%m-%d %H:%M:%S"
 
